environment: "Development"

api:
  port: 9000
  connectionString: ""

consumer:
  bootstrapServer: localhost:9093
  groupId: worker_consumer_group
  topic: kafka_poc_server.dbo.Customers
  slackBaseUrl: slackBaseUrl
